### ISSUE TITLE
**Render Error**: "Can't find variable: React"

### ISSUE THREAD

**Issue by phillip9077** [birkir/react-native-sfsymbols#12]
A similar error was mentioned a while ago [here](https://github.com/birkir/react-native-sfsymbols/issues/2#issue-790751499), but I just npm install'd the package and the error in the title occurred for me. Maybe the npm package isn't the most updated one? 

Please let me know, thank you!

Edit: 
<img width="365" alt="Screen Shot 2021-06-23 at 1 39 37 PM" src="https://user-images.githubusercontent.com/50229060/123041884-9051ea80-d428-11eb-9538-c11dfab8c4d2.png">

**Comment by MoOx** [comment]
Can you try directly my fork just to see if that is working better? use `npm install https://github.com/MoOx/react-native-sfsymbols`

**Comment by birkir** [comment]
Should be fixed now

**Comment by phillip9077** [comment]
Hey, sorry for replying so late! The error disappeared, but no icons are being displayed. 

Here is a minimal code example of what I have so far (basically copied and pasted the sample code): 

```
import React from "react";
import { StyleSheet, SafeAreaView } from "react-native";
import {SFSymbol} from "react-native-sfsymbols";

class ExploreFeed extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <SafeAreaView style={styles.main}>
                <SFSymbol
                    name="thermometer.sun.fill"
                    weight="semibold"
                    scale="large"
                    color="red"
                    size={16}
                    resizeMode="center"
                    multicolor={false}
                    style={{ width: 32, height: 32 }}
                />
            </SafeAreaView>
        )
    }
}

const styles = StyleSheet.create({
    main: {
        backgroundColor: "#272727",
        height: "100%",
        alignItems: "center",
        justifyContent: "center"
    },
});

export default ExploreFeed
```

Edit: I tried running the npm install given by @MoOx, but that failed in terminal for some reason. I'm not sure if it'll help but I'm currently running this on a new M1 MacBook Pro.

**Comment by birkir** [comment]
You are using iOS 14+ simulator?

**Comment by phillip9077** [comment]
Yes, I am running an iPhone 12 iOS 14.3 simulator.

**Comment by birkir** [comment]
Can you try running the example provided in the repo?

**Comment by phillip9077** [comment]
Sure, that's what I did in the minimal code I posted above. I tried it again by actually making a new file and copy pasting the example provided in the repo. Same results :(
```
import React from "react"
import { SFSymbol } from "react-native-sfsymbols";

export function Example() {
  return (
    <SFSymbol
      name="thermometer.sun.fill"
      weight="semibold"
      scale="large"
      color="red"
      size={16}
      resizeMode="center"
      multicolor={false}
      style={{ width: 32, height: 32 }}
    />
  );
}

export default Example
```

**Comment by birkir** [comment]
Works well for me, steps I did:

```
npx react-native init example --template react-native-template-typescript
cd example
yarn add react-native-sfsymbols
cd ios
pod install
```

Pasted this into App.tsx:
```tsx
import React from 'react';
import {StyleSheet, SafeAreaView} from 'react-native';
import {SFSymbol} from 'react-native-sfsymbols';

class ExploreFeed extends React.Component {
  render() {
    return (
      <SafeAreaView style={styles.main}>
        <SFSymbol
          name="thermometer.sun.fill"
          weight="semibold"
          scale="large"
          color="red"
          size={16}
          resizeMode="center"
          multicolor={false}
          style={styles.icon}
        />
      </SafeAreaView>
    );
  }
}

const styles = StyleSheet.create({
  main: {
    backgroundColor: '#272727',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  icon: {
    width: 32,
    height: 32,
  },
});

export default ExploreFeed;
```

**Comment by birkir** [comment]
![simulator_screenshot_42AF995C-F21D-45B5-9B99-9190842E58BB](https://user-images.githubusercontent.com/180773/123618218-8567d300-d7f7-11eb-88f6-fa972ceb6fcb.png)

**Comment by andrew-levy** [comment]
@phillip9077 It works well for me now. Try restarting your metro bundler and re run your run ios command

**Comment by phillip9077** [comment]
Sorry for replying so late! I'm not sure what went wrong with my code (surprise surprise), but it works now. Thanks for all the quick responses!

**Comment by greenafrican** [comment]
> Works well for me, steps I did:
> 
> ```
> npx react-native init example --template react-native-template-typescript
> cd example
> yarn add react-native-sfsymbols
> cd ios
> pod install
> ```
> 
> Pasted this into App.tsx:
> 
> ```tsx
> import React from 'react';
> import {StyleSheet, SafeAreaView} from 'react-native';
> import {SFSymbol} from 'react-native-sfsymbols';
> 
> class ExploreFeed extends React.Component {
>   render() {
>     return (
>       <SafeAreaView style={styles.main}>
>         <SFSymbol
>           name="thermometer.sun.fill"
>           weight="semibold"
>           scale="large"
>           color="red"
>           size={16}
>           resizeMode="center"
>           multicolor={false}
>           style={styles.icon}
>         />
>       </SafeAreaView>
>     );
>   }
> }
> 
> const styles = StyleSheet.create({
>   main: {
>     backgroundColor: '#272727',
>     height: '100%',
>     alignItems: 'center',
>     justifyContent: 'center',
>   },
>   icon: {
>     width: 32,
>     height: 32,
>   },
> });
> 
> export default ExploreFeed;
> ```

Following these exact steps I still get "Can't find variable: React" on iPhone 13 iOS 15.0
![Simulator Screen Shot - iPhone 13 - 2021-11-09 at 13 04 11](https://user-images.githubusercontent.com/1160732/140913370-af12f51f-0c7e-4d89-bd49-e0a727977313.png)

**Comment by 343max** [comment]
Following exactly the same steps, seeing exactly the same `can't find variable React` error.
