### ISSUE TITLE
ReferenceError: Property 'React' doesn't exist

### ISSUE THREAD

**Issue by svbutko** [birkir/react-native-sfsymbols#15]
When generating an update to a new version (1.2.0) the JS files were incorrectly built in lib folder:

Now there are two files instead of one:

index.ios.js
index.js

And the same for typings.

And this leads to a crash

**Comment by svbutko** [comment]
Returning 
`import React, { PureComponent } from "react";`

To

`import * as React from "react";`

Fixes it but it's incorrect and there's a flaw in tsconfig

**Comment by 343max** [comment]
When copying and pasting [index.tsx](https://github.com/birkir/react-native-sfsymbols/blob/main/src/index.tsx) into a file inside the project everything works just fine.
