### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by MoOx** [birkir/react-native-sfsymbols#3]
Answering my own question for futur users:

I did some [research](https://twitter.com/MoOx/status/1346195696169476098) and it seems *it can't be done, legally speaking*.  

tldr: **_SF Symbols_**:
- **can only be used on Apple devices** in native apps ❤️ 💻📱⌚️🖥
- ⚠️ **can NOT be shared** as a font, as PNG etc, and cannot be used on non Apple devices 💔 🤖

More info:
- [React Native Vector Icons request](https://github.com/oblador/react-native-vector-icons/issues/1015) (I posted a similar comment there) 
- <https://sfsymbols.com> got this exact problem: the site was embedding PNG version of the assets, and [got an Apple layer asking for removal](https://noahgilmore.com/blog/taking-down-sfsymbols/), which [has been](https://github.com/noahsark769/sfsymbols.com/commit/8fab0f5e4bd03148e3b17cbaa6d9ebababa883e4) [done](https://github.com/noahsark769/sfsymbols.com/commit/5aa25694681a176adc137b3401a3e6dba2b81fe3)

**Comment by MoOx** [comment]
So closing as we cannot (and should not!) do this :)

**Comment by birkir** [comment]
We could still do it for older iOS devices.
What I had in mind was a script to export all the icons as SVG

https://github.com/davedelong/sfsymbols

**Comment by MoOx** [comment]
This script doesn't work with SF Symbols 2 because the font has been tweaked by Apple to make it harder to work with it 😅

Anyway, I already have all SVG exported in a folder. Let's continue to discuss about that in #1 :)
